  $( function() {
    var availableTags = [
      "Copy an Employee ",
      "Standard Hours and Earnings",
      "Calculation Maintenance",
      "Electronic Pay Statements (E-Stubs)",
      "Non-payroll Payees",
      "PAYweb, ROE Service Form Steps 1-3",
      "Errors and Warnings",
      "Terminations",
      "Additional Payroll Runs",
      "Vacation Pay",
      "Accrual Payouts",
      "Groovy",
      "Alternate Entry",
      "Quick Entry",
      "View Reports",
      "Receive Time",
      "Receive From HR",
      "ROE Request",
      "2016/2017 Holiday Schedule and Year End Tips",
      "E-Tax Form Set Up",
      "E-Tax Form-Employee Consent",
      "2016 PIER Report Guide",
      "Year End and New Year Checklist",
      "The New Progress Bar",
      "Year End Options",
      "Tax Form Options",
      "Create RL-1 Summary",
      "2016/2017 Holiday Schedule and Year End Ti",
      "TD1 Forms",
      "Source Deductions Return (QUEBEC)",
      "Understanding Reports",
      "View Current ADJ",
      "View History",
      "SFTP File Transfer",
      "Month End Y field",
      "Vacation Accrual",
      "Changing your Bus. No. or PPERLIST",
      "Manual Cheques",
      "YTD Entry",
      "Additional Reports",
      "Additional Reports 2",
      "Employee Occupation",
      "Accrual Reset",
      "Edit G/L Groups",
      "Modify Prior Year EI History",
      "Changes to the FUNDSOUT Report",
      "Spring 2017 Enhancements",
      "2017 Government Legislative Changes",
      "What to Expect at Yearend",
      "2016 Government Rates",
      "PAYweb’s New Look and Feel",
      "Self-Service Password Reset",
      "Statutory Holidays"
    ];
    $( "#text-search" ).autocomplete({
      source: availableTags
    });
  } );
